### ISSUE TITLE
 The namespace `global::' already contains a definition for `Separation'

### ISSUE THREAD

**Issue by phpchess** [antonpantev/unity-movement-ai#1]
Getting the error:
 The namespace `global::' already contains a definition for`Separation' and also
 error CS0101: The namespace `global::' already contains a definition for`Cohesion'.
General wording in definitions is always an issue and leads to conflicts with other asset packaged. maybe you can pre-fix all your classes and references to them with umai_ and then these conflicts would be less likely to arise. Thanks though for a great library of behaviours. Works really well.

**Comment by sturdyspoon** [comment]
I agree. I've always intended to add a namespace to the library (why I forgot to do it from the beginning is beyond me).

**Comment by sturdyspoon** [comment]
I added a namespace to the [dev](/antonpantev/unity-movement-ai/tree/dev) branch.
