### ISSUE TITLE
Debug library?

### ISSUE THREAD

**Issue by nicmar** [antonpantev/unity-movement-ai#10]
Hi, very impressive library! I'm trying it out right now, on the dev branch, :)

There are some references to a class called DebugDraw in Wander1.cs, which seems useful. Can you share that code? 

            //		DebugDraw debugDraw = gameObject.GetComponent<DebugDraw> ();
            //		debugRing = debugDraw.createRing (Vector3.zero, wanderRadius);

Thanks!

**Comment by sturdyspoon** [comment]
I don't have the code for it anymore since I wasn't really using it. It only had one function in it `createRing()` and all the function did was instantiate a prefab of a ring. So unfortunately it wasn't very useful.

**Comment by nicmar** [comment]
No problem, it’s a great library (the dev branch works great) and we will definitely mention you in the credits of the game we’re making. :)

**Comment by sturdyspoon** [comment]
Thats awesome :D Good luck with your game!
